# Generated by Django 2.1 on 2018-10-29 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('dateOfExam', 'session')},
        ),
    ]
