# Generated by Django 2.1.1 on 2018-09-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allotment', '0002_delete_garbagetable'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('timetable_id', 'dateOfExam')},
        ),
    ]
